apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-nfs-storage
              mountPath: /data/db
      volumes:
        - name: mongo-nfs-storage
          nfs:
            server: 192.168.31.240
            path: /data/mongodb 
            
---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 27017
  selector:
    name: mongo