apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    # FIXME: use the right IP
    server: 192.168.31.240
    path: "/data/mysql/data"
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.conf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
    lower_case_table_names=1
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    k8s-app: mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          value: "hicoindev*!*"
        ports:
        - containerPort: 3306 
          name: mysql
        volumeMounts: 
          - name: mysql-pv 
            mountPath: /var/lib/mysql  
          - name: config
            mountPath: /etc/mysql/conf.d/
            readOnly: true
      volumes: 
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: config
          configMap:
            name: mysql-config
---

apiVersion: v1 
kind: Service 
metadata: 
  name: mysql 
  labels: 
    k8s-app: mysql
spec: 
  type: NodePort
  ports: 
    - port: 3306 
      targetPort: 3306
      nodePort: 3306 
  selector: 
    k8s-app: mysql 
