apiVersion: v1
kind: ConfigMap
metadata:
  name: messagebroker-config
data:
  appsettings.json: |
    {
      "EQueue": {
        "BrokerStorePath": "/data/hicoin-equeue-store",
        "NameServerAddress": "messagenameserver:10000"
      }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: messageadminweb-config
data:
  appsettings.json: |
    {
      "EQueue": {
        "NameServerAddress": "messagenameserver:10000"
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hicoin-chat-processorhost-config
data:
  appsettings.json: |
    {
      "ENode": {
        "EventStoreConnectionString": "Datasource=mysql;Database=hicoin_chat_eventstore;uid=root;pwd=hicoindev*!*;Allow User Variables=True;"
      },
      "EQueue": {
        "NameServerAddress": "messagenameserver:10000"
      },
      "MongoDb": {
        "ConnectionString": "mongodb://mongo:27017/hicoin-chat",
        "DatabaseName": "hicoin-chat"
      },
      "Redis": {
        "ConnectionString": "redis-master:6379,keepAlive=60,abortConnect=false,connectTimeout=5000,syncTimeout=5000",
        "DatabaseId": "1"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hicoin-chat-web-config
data:
  appsettings.json: |
    {
      "ENode": {
        "EventStoreConnectionString": "Datasource=mysql;Database=hicoin_chat_eventstore;uid=root;pwd=hicoindev*!*;Allow User Variables=True;"
      },
      "EQueue": {
        "NameServerAddress": "messagenameserver:10000"
      },
      "MongoDb": {
        "ConnectionString": "mongodb://mongo:27017/hicoin-chat",
        "DatabaseName": "hicoin-chat"
      },
      "Redis": {
        "ConnectionString": "redis-master:6379,keepAlive=60,abortConnect=false,connectTimeout=5000,syncTimeout=5000",
        "DatabaseId": "1"
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hicoin-content-processorhost-config
data:
  appsettings.json: |
    {
      "ENode": {
        "EventStoreConnectionString": "Datasource=mysql;Database=hicoin_content_eventstore;uid=root;pwd=hicoindev*!*;Allow User Variables=True;"
      },
      "EQueue": {
        "NameServerAddress": "messagenameserver:10000"
      },
      "MongoDb": {
        "ConnectionString": "mongodb://mongo:27017/hicoin-content",
        "DatabaseName": "hicoin-content"
      },
      "Redis": {
        "ConnectionString": "redis-master:6379,keepAlive=60,abortConnect=false,connectTimeout=5000,syncTimeout=5000",
        "DatabaseId": "1"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hicoin-content-config
data:
  appsettings.json: |
    {
      "ENode": {
        "EventStoreConnectionString": "Datasource=mysql;Database=hicoin_content_eventstore;uid=root;pwd=hicoindev*!*;Allow User Variables=True;"
      },
      "EQueue": {
        "NameServerAddress": "messagenameserver:10000"
      },
      "MongoDb": {
        "ConnectionString": "mongodb://mongo:27017/hicoin-content",
        "DatabaseName": "hicoin-content"
      },
      "Redis": {
        "ConnectionString": "redis-master:6379,keepAlive=60,abortConnect=false,connectTimeout=5000,syncTimeout=5000",
        "DatabaseId": "1"
      }
    }
